name: Main

on:
  push:
    branches:
      - master

env:
  PACKAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PACKAGES_USERNAME: ${{ github.actor }}
  REPO_NAME: ${{ github.event.repository.name }}

jobs:

  build-publish-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Language-Start-Point image, test it
        run: ./run_tests.sh